### PR TITLE
Day 15 Chiton

### LINKED ISSUE #16: Poor Performance in Challenge #day15
Challenge #15 part 2 took >14 min to find the path. I'll need to improve the solution.

`go run main02.go  854.83s user 2.78s system 99% cpu 14:17.70 total`

### PR DESCRIPTION
**Pull request by luisandani**

### CODE REVIEW

**Comment by luisandani** [comment]
part 2 takes over 14 minutes to calculate the path... I need to find a more performant solution. I think other people used heaps

**Comment by risangpinto** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
adamjtoth, @mbleuer, @usurpedunicorn, @kalkulusteam, @ParaXY, @ktoulgaridis, @germayneng, @DylanCkawalec, @skwongg, @maxrugen, @newmanicspree, @AdamBouhmad, @sidorov-alex, @ArdeshirV, @girish, @Cryptotalkz, @ttufekci, @jasperfurniss, @MecH4nics, @rahulrajaram, @OmarAberkan, @AlphaKilo35, @tvu2092, @Ferg40, @seanwilliams90, @sedd900, @nickolasburr, @s-daemen, @frikke, @luyongxu, @vietquocnguyen, @JBetser, @lexbeelen, @GeertSl, @Cerv1, @sehue, @cengebretson, @fentas, @mmeisels, @sstoner, @pilsy, @samupra, @cleitontortato, @kennethpdev, @brucewillis88, @andrewcockerham, @fabiotnt, @oklamos, @chromeNexus, @Jerome1337

**Comment by risangpinto** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by risangpinto** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Pull request merged**
